#!/bin/bash
#PBS -l nodes=1:ppn=1,walltime=0:20:00
#PBS -N app-classifiedfibertractstats
#PBS -V

#if [ $ENV == "IUHPC" ]; then
#	cd $PBS_O_WORKDIR
#	module load matlab
#fi

rm .f finished

rm *.csv

#export MATLABPATH=$MATLABPATH:$SERVICE_DIR
#matlab -nodisplay -nosplash -r main

module load singularity 2> /dev/null

singularity exec -e docker://brainlife/mcr:neurodebian1604-r2017a ./msa/main

if [ -s output_FiberStats.csv ]; 
then 
  echo 0 > finished
else
  echo "file missing"
  echo 1 > finished
  exit 1
fi
